export type Cell = { x: number; y: number };
export type DinoObstacle = { x: number; w: number; h: number; y: number; bird: boolean };

export const play = {
  snakeTimer: null as number | null,
  snakeProbe: null as number | null,
  snakeBody: [] as Cell[],
  snakeDir: { x: 1, y: 0 },
  snakeNext: { x: 1, y: 0 },
  snakeFood: { x: 7, y: 7 },
  snakeScore: 0,
  snakeOver: false,
  snakeEpoch: 0,
  snakeShown: false,
  snakeAiBusy: false,
  snakeRunning: false,
  backends: { jev: false, laya: false },
  layaBase: "http://127.0.0.1:8100",
  snakeSteerNote: "",
  dinoRaf: null as number | null,
  dinoRunning: false,
  dinoOver: false,
  dinoScore: 0,
  dinoBest: Number(localStorage.getItem("pi-auto-dino-best") || 0) || 0,
  dinoY: 0,
  dinoVy: 0,
  dinoDuck: false,
  dinoSpeed: 2.4,
  dinoObstacles: [] as DinoObstacle[],
  dinoGap: 220,
  dinoLeg: 0,
  dinoLast: 0,
  dinoEpoch: 0,
  dinoSteerNote: "",
  dinoAsking: false,
};
